### DISCUSSION TITLE
eframe::App::update doesn't render everything

### DISCUSSION THREAD

**Discussion by niyrme** [emilk/egui#1929] [Q&A]
For whatever reason only the first element inside of the horizontal layout gets drawn. If i swap the vertical ones the capture doesn't show up, but the log does.
The image is 768x480 if that's relevant.

```rust
let img = ...;
egui::CentralPanel::default().show(ctx, |ui| {
   ui.horizontal(|ui| {
      ui.vertical(|ui| {
         ui.heading("Capture");
         ui.separator();
         img.show(ui);
      });

      ui.separator();

      ui.vertical(|ui| {
         ui.heading("Log");
         ui.separator();

         for l in self.logs.iter() {
            ui.label(l.to_string());
         }
      });
   });
});
```

Dependency Versions
```toml
[dependencies]
egui = { version = "0.18", features = ["ron"] }
egui_extras = { version = "0.18", features = ["image"] }
image = "0.24"
# more non-relevant ones here
```
