### DISCUSSION TITLE
Issues building the hello world example?

### DISCUSSION THREAD

**Discussion by furrz** [emilk/egui#2210] [Q&A]
I've tried to run the `hello-world` code from this repo and I'm getting:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
```

My cargo.toml looks like so, I even copied the `rust-version` value from the hello-world example:

```toml
[package]
name = "rusted"
version = "0.1.0"
rust-version = "1.61"
edition = "2021"

[dependencies]
eframe = "0.19.0"
```

Most interestingly, it builds *fine* if I clone egui directly and `cd` into the `examples/hello_world` folder instead of making my own copy that uses the published `eframe` crate... *and* `rustc --version` returns a different result, even though I have `rust-version` set here!?

Does egui require the use of an unstable build of rust but just... not document this anywhere? Or is something going very wrong here? I've tried to ensure my rust version is up to date using `rustup update`.
