### DISCUSSION TITLE
Try to use egui in Android

### DISCUSSION THREAD

**Discussion by ssrlive** [emilk/egui#2874] [Q&A]
I'm try to writing a pure Rust app in Android, but failed, the wedgets not displayed. here is my `Cargo.toml` and `lib.rs` files. how to resolve it?

this is the full code.  [native-demo.zip](https://github.com/emilk/egui/files/11144056/native-demo.zip)

Cargo.toml
```toml
[package]
name = "nativedemo"
version = "0.0.1"
authors = ["Nikita Krupitskas <krupitskaz@gmail.com>"]
edition = "2021"

[dependencies]
eframe = { version = "0.21", features = [ "wgpu" ] }
egui_demo_lib = "0.21"
log = "0.4"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13"
winit = { version = "0.28", default-features = false, features = [ "android-native-activity" ] }

[lib]
crate-type = ["cdylib", "lib"]
```

lib.rs
```
#[cfg(target_os = "android")]
#[no_mangle]
fn android_main(app: winit::platform::android::activity::AndroidApp) {
    use winit::platform::android::EventLoopBuilderExtAndroid;

    android_logger::init_once(
        android_logger::Config::default().with_max_level(log::LevelFilter::Info),
    );

    let mut options = NativeOptions::default();
    options.event_loop_builder = Some(Box::new(move |builder| {
        builder.with_android_app(app);
    }));
    main_entry(options);
}

use eframe::egui;
use eframe::{NativeOptions, Renderer};

#[derive(Default)]
struct DemoApp {
    demo_windows: egui_demo_lib::DemoWindows,
}

impl eframe::App for DemoApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.demo_windows.ui(ctx);
    }
}

pub fn main_entry(mut options: NativeOptions) {
    options.renderer = Renderer::Wgpu;
    let _ = eframe::run_native(
        "My egui App",
        options,
        Box::new(|_cc| Box::new(DemoApp::default())),
    );
}
```
