### DISCUSSION TITLE
how to specify correct bytesloader for images on fs

### DISCUSSION THREAD

**Discussion by Ragnyll** [emilk/egui#4361] [Q&A]
Hey, is there a feature i need to include a bytesloader to load an image i define from my fs? I have the these features on egui_extras and image
```toml
  egui_extras = { version = "0.27.2", features = ["default", "image", "file"]} 
  image = {version = "0.25", default-features = false, features = ["jpeg", "png"]} 
```

and this is how im calling my image: 

```rust
let asset_dir: PathBuf = self.asset_dir.clone();
let full_image_path = format!(
    "{}{}",
    asset_dir.to_str().unwrap(),
    card_image_path.to_str().unwrap()
);
if ui.add(egui::widgets::ImageButton::new(egui::Image::new(full_image_path))).clicked()
```
I am including image loaders in my main.rs

```rs
    eframe::run_native(
        "Combat Crew",
        native_options,
        Box::new(|cc| {
            egui_extras::install_image_loaders(&cc.egui_ctx);
            Box::new(combat_crew_client::TemplateApp::new(cc))
        }),
    )
```

![2024-04-13-211030_981x425_scrot](https://github.com/emilk/egui/assets/10107987/d83c6522-bfd6-4ce3-bfc0-6723444b3ce0)
