### DISCUSSION TITLE
How do I use the http feature in the code specified in template repo?

### DISCUSSION THREAD

**Discussion by trickster** [emilk/egui#486] [Q&A] [answered]
Hi,

HTTP feature described here, how do I import into my code? Feature list specified in that toml, doesn't seem to be exported?
https://github.com/emilk/egui_template/blob/master/Cargo.toml#L19

If I explicitly specify this way, I could use HTTP features
```toml
[dependencies]
eframe = { version = "0.12.0", features = ["http"] }
```

instead of this
```toml
[dependencies]
eframe = "0.12.0"

[features]
default = []
http = ["eframe/http"] # Enable if you want to do http requests
```
