### ISSUE TITLE
Missing WASM setup docs related to ahash/getrandom

### ISSUE THREAD

**Issue by elimerl** [emilk/egui#2009]
I was trying to setup egui for a WASM project, and it took about 15 minutes of searching to find that I had to manually add getrandom as a dependency for it to work on WASM:
```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
```

If possible there should be clearer documentation for setting up on WASM, specifically for this issue. I had to look at commit [5514a8afda53c282d2be670bef657d5c7812d467](https://github.com/emilk/egui/commit/5514a8afda53c282d2be670bef657d5c7812d467#diff-4dd39592779c181442ec4b5a91f925e8ca93612257f81aef60d3f120d74e3647R97) to find the solution.

Thanks!
