### ISSUE TITLE
Enable accessibility by default in egui demo app

### ISSUE THREAD

**Issue by ChrisJefferson** [emilk/egui#2960]
I was interested in accessibility in egui, so I decided to try it out in the demo app.

First problem -- it's not enabled by default, I had to go into egui_demo_app/Cargo.toml and remove "default-features=false" from eframe (there may be a better way of doing this?)

Some other immediate issues are:

1) The icons in the title bar are being passed, and described, so for example I hear "2 o'clock fractal clock'

**Comment by AutoSponge** [comment]
```toml
eframe = { workspace = true, default-features = true, features = ["web_screen_reader"] }
egui = { workspace = true, features = ["callstack", "default"] }
egui_demo_lib = { workspace = true, features = ["default", "chrono"] }
egui_extras = { workspace = true, features = ["default", "image"] }
image = { workspace = true, default-features = true, features = [
```

I changed these two in `/egui/crates/egui_demo_app/Cargo.toml` to enable VoiceOver on Mac. This is a huge improvement over similar libraries where nothing works, kudos.

A few notes: 
- links still identify as "text"
- only the "window spots" rotor menu is populated (and only has app window and darkmode button). Getting landmarks, buttons, and links to populate would really help navigation with a screenreader.
- navigating to a "group" (any of the canvas widgets) works but you can't toggle the collapse or move. These could be exposed as buttons for this to work better.
- (side note) the light theme has poor color contrast for links 

I don't know Rust but I know accessibility and may be able to help.
