### ISSUE TITLE
Segmentation fault on WSL 2

### ISSUE THREAD

**Issue by ClementNerma** [emilk/egui#3208]
Hi there!

I'm currently learning egui to make a comic reader application, and have a bit of trouble making it work.

I'm using WSL 2 on Windows 11. On my first PC, everything works fine, but on my second I get a segmentation fault. Here is the minimal reproduction example I've gotten to:

```rust
use eframe::{App, NativeOptions};

fn main() -> eframe::Result<()> {
    eframe::run_native(
        "reader",
        NativeOptions::default(),
        Box::new(|_| Box::new(MyApp)),
    )
}

struct MyApp;

impl App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {});
    }
}
```

The `update` function runs and the inner closure too, but I get a segmentation fault afterwards. I don't get to see any window displayed before the crash.

I'm currently using the latest version of `egui` and `eframe`, here is my `Cargo.toml`:

```toml
[package]
name = "reader"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.22.0", default-features = false, features = ["glow"] }
egui = "0.22.0"
```

Any idea of what's causing this?
