### ISSUE TITLE
image in ScrollArea jitters

### ISSUE THREAD

**Issue by GaN8373** [emilk/egui#3455]
```toml
[dependencies]
egui = "0.23.0"
eframe = { version = "0.23.0", default-features = false, features = [
    "accesskit",    
    "default_fonts",
    "glow",          
    "persistence",   
] }
egui_extras = { version = "0.23.0",features = ["all_loaders"] }
image = { version = "0.24", features = ["jpeg", "png"] }
```

```rust

fn gen_image<'a>() -> Image<'a> {
    Image::new("file://assets/icon-256.png")
        .max_width(42.0)
        .rounding(10.0)
}
pub(crate) fn default(app: &mut TemplateApp, ctx: &Context) -> InnerResponse<()> {
    egui::SidePanel::left("left_panel_1")
        .width_range(Rangef::new(20.0, 50.0))
        .show(ctx, |ui| {
            egui::ScrollArea::vertical().show(ui, |ui| {
                ui.add(gen_image()).on_hover_text("item 1");
                ui.add(gen_image()).on_hover_text("item 2");
                ui.add(gen_image()).on_hover_text("item 3");
                ui.add(gen_image()).on_hover_text("item 4");
                ui.add(gen_image()).on_hover_text("item 5");
                ui.add(gen_image()).on_hover_text("item 6");
                ui.add(gen_image()).on_hover_text("item 7");
                ui.add(gen_image()).on_hover_text("item 8");
                ui.add(gen_image()).on_hover_text("item 9");
                ui.add(gen_image()).on_hover_text("item 10");
                ui.add(gen_image()).on_hover_text("item 11");
                ui.add(gen_image()).on_hover_text("item 12");
                ui.add(gen_image()).on_hover_text("item 13");
                ui.add(gen_image()).on_hover_text("item 14");
                ui.add(gen_image()).on_hover_text("item 15");
            });
        })
}

```

https://github.com/emilk/egui/assets/80253667/1b234868-5b7e-4f41-8f74-8626da1ed761

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser edge 117.0.2045.41
 - Version egui 0.23.0
