### ISSUE TITLE
displayed image is bigger than it should be (scaled up when it shouldn't)

### ISSUE THREAD

**Issue by Frefreak** [emilk/egui#3687]
**Describe the bug**
I notice the displayed image appears to be scaled up, so the text on it becomes blurry, makes it very noticeable.

Native window, not web.

example code modified from `examples/image`

```rust
use eframe::egui;

fn main() -> Result<(), eframe::Error> {
    env_logger::init(); // Log to stderr (if you run with `RUST_LOG=debug`).
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default().with_inner_size([1600., 900.]),
        ..Default::default()
    };
    eframe::run_native(
        "Image Viewer",
        options,
        Box::new(|cc| {
            // This gives us image support:
            egui_extras::install_image_loaders(&cc.egui_ctx);
            Box::<MyApp>::default()
        }),
    )
}

#[derive(Default)]
struct MyApp {}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        let img = egui::Image::new("file:///path/to/test.png");
        egui::CentralPanel::default().show(ctx, |ui| {
            egui::ScrollArea::both().show(ui, |ui| {
                ui.add(img.fit_to_original_size(1.));
            });
        });
    }
}
```

Cargo.toml:

```toml
[package]
name = "asdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.1"
egui_extras = { version = "0.24.1", features = ["all_loaders"] }
env_logger = "0.10.1"

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", branch = "master" }
# if you're using eframe:
eframe = { git = "https://github.com/emilk/egui", branch = "master" }

```

**To Reproduce**
1. prepare a not so big image so its easy to fit in one screen
2. use the above code to display
3. run

**Expected behavior**
image looks the same as being viewed by other normal image viewer like feh

**Screenshots**
![image](https://github.com/emilk/egui/assets/7122156/997ef0d9-f9c5-4fb6-b45e-77b1e1d0766e)

I put them side by side so its obvious that its scaled up.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox, but not relevant here

**Additional context**
I feels like it is because I have setup my global display to be 112.5% in system display setting. If I pass `fit_to_original_size(1./1.125)` the image looks normal.

![image](https://github.com/emilk/egui/assets/7122156/2e319b18-1cde-4481-9226-a851a3b499c7)

However I don't remember seeing this behavior in other image viewer I use.
