### ISSUE TITLE
Add Syntect custom syntax & themes support

### ISSUE THREAD

**Issue by antaalt** [emilk/egui#3964]
Hello, 
I am trying to work with the syntect code editor which is great, the issue I have now is that it seems impossible to load custom syntax & themes to add support for others languages than the one [available by default](https://github.com/sublimehq/Packages/) in sublime text, maybe I just missed the API, but it would be nice to be able to load a custom tmTheme and sublime-syntax as Syntect support this via `SyntaxSetBuilder`.

From what I saw, egui run `syntect::parsing::SyntaxSet::load_defaults_newlines()` which is created with the cache, but we could somehow allow egui to load custom themes & syntax aswell

**Comment by TimTheBig** [comment]
**Any progress?**
I would be open to **writing a patch** that allows for loading of a  syntax highlighting theme from a `.tmTheme`(sublime theme) file.
I just wanted to know if there is any reason that this is not implemented?

**Comment by antaalt** [comment]
Didn't had the time to look into it. It does not look like a highly requested feature, which would explain why it's not implemented

**Comment by mkeeter** [comment]
I would also be interested in this functionality, since I want to embed [Rhai](https://rhai.rs/) scripts into an `egui`-based application.  I'll investigate and possibly open a PR depending on difficulty.

**Comment by mkeeter** [comment]
I've implemented this in #7084 , and backported to 0.31.1 [here](https://github.com/mkeeter/egui/tree/custom-syntect-settings-0.31.1-backport).

You can test it out with something like this:

```toml
[dependencies]
egui_extras = { git = "https://github.com/mkeeter/egui", features = ["syntect"], branch = "custom-syntect-settings-0.31.1-backport" }

[patch.crates-io]
egui = { git = "https://github.com/mkeeter/egui", branch = "custom-syntect-settings-0.31.1-backport" }
epaint = { git = "https://github.com/mkeeter/egui", branch = "custom-syntect-settings-0.31.1-backport" }
```
