### ISSUE TITLE
Firefox panic with parking_lot (Parking not supported on this platform)

### ISSUE THREAD

**Issue by zdimension** [emilk/egui#4405]
Similar to #1401. This issue is a series in my attempt to use `request_repaint` from Web Workers (previous one was #4368).

**Describe the bug**

When called from a Web Worker, `Context::request_repaint` calls `Context::viewport_id` which calls `RawRwLock::lock_shared_slow` which uses `ThreadParker` which doesn't seem to be supported on Firefox.

![image](https://github.com/emilk/egui/assets/4533568/19cd00e9-c4e5-4727-a40c-2500069a39ed)

**To Reproduce**

Call `request_repaint` from a Web Worker on Firefox.

**Workarounds**

I just end up not calling `request_repaint` from a Web Worker and instead call `request_repaint_after` in my main thread with some fixed time like 1/60 s.

**Desktop (please complete the following information):**
 - Browser: Firefox 124

**Comment by white-axe** [comment]
You need to enable the `nightly` feature of parking_lot

**Comment by zdimension** [comment]
> You need to enable the `nightly` feature of parking_lot

Thanks, this fixed it (though, was this documented anywhere in egui?), though since the `stdsimd` feature was renamed to `stdarch_wasm_atomic_wait`, the latest crates.io release of parking_lot doesn't work as is, I had to manually patch parking_lot_core to use the Git repo which contains the fix:

```toml
[patch.crates-io]
# TODO: update this when parking_lot_core > 0.9.9 is released
# https://github.com/Amanieu/parking_lot/pull/435#issuecomment-2072218790
parking_lot_core = { git = "https://github.com/Amanieu/parking_lot" }
```

And, then run `cargo update` to fetch it of course.

This patch will be necessary until the next release of parking_lot_core.

Keeping this open since @emilk [kept my other issue open](https://github.com/emilk/egui/issues/4368#issuecomment-2076595211) as a reminder to add to docs or add the feature in eframe. Feel free to close it if it's not relevant
