### ISSUE TITLE
Displaying a JPEG image does not work with `image` crate version higher than 0.24

### ISSUE THREAD

**Issue by leogomezz4t** [emilk/egui#4464]
I was recently trying to display a JPEG image in a egui window using eframe but it would consistently say "Image format JPEG not supported". When trying to display a PNG, it worked perfectly however. To be clear, I had already included the jpeg features in my Cargo.toml.

I found the only thing that fixed it was changing the `image` crate version from `0.25.1` to `0.24`.

I am using this test code pulled from the egui image example

```rust
use eframe::egui;

fn main() -> Result<(), eframe::Error> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default().with_inner_size([600.0, 800.0]),
        ..Default::default()
    };
    eframe::run_native(
        "Image Viewer",
        options,
        Box::new(|cc| {
            // This gives us image support:
            egui_extras::install_image_loaders(&cc.egui_ctx);
            Box::<MyApp>::default()
        }),
    )
}

#[derive(Default)]
struct MyApp {}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            egui::ScrollArea::both().show(ui, |ui| {
                ui.add(
                    egui::Image::new("https://picsum.photos/seed/1.759706314/1024").rounding(10.0),
                );
            });
        });
    }
}
```

This Cargo.toml doesn't work
```toml
[package]
name = "image_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", features = [
    "default"
] }
egui = "0.27.2"
egui_extras = { version = "0.27.2", features = ["default", "all_loaders"] }
# Only difference is the image version is 0.25.1
image = { version = "0.25.1", default-features = false, features = [
    "jpeg",
    "png"
] }

```

This Cargo.toml does work
```toml
[package]
name = "images"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27.2", features = [
  "default",
] }
egui = "0.27.2"
egui_extras = { version = "0.27.2", features = ["default", "all_loaders"] }
# Only difference is the image version is 0.24
image = { version = "0.24", default-features = false, features = [
  "jpeg",
  "png",
] }
```
