### ISSUE TITLE
Wayland dependencies are pulled in for eframe, even when `wayland` feature is disabled.

### ISSUE THREAD

**Issue by crumblingstatue** [emilk/egui#4538]
**Describe the bug**
When depending on eframe with default features disabled, and only `x11` and `glow` enabled, eframe is pulling in wayland dependencies.

**To Reproduce**
Create a new project, and depend on `eframe` with default features disabled.
```toml
[package]
name = "myeframetest"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { git = "https://github.com/emilk/egui.git, default-features = false, features = ["glow", "x11"] }
```

**Expected behavior**

No wayland dependencies in `Cargo.lock`

**What happens**
`Cargo.lock` has several wayland dependencies.
