### ISSUE TITLE
DX12 not working with eframe

### ISSUE THREAD

**Issue by kametsuu** [emilk/egui#4885]
**Describe the bug**
DirectX12 doesn't work with eframe and errors with error:
```
[2024-07-28T19:05:15Z ERROR eframe::native::run] Exiting because of error: WGPU error: Failed to create surface for any enabled backend: {} during event Resumed
Error: Wgpu(CreateSurfaceError(CreateSurfaceError { inner: Hal(FailedToCreateSurfaceForAnyBackend({})) }))
error: process didn't exit successfully: `target\debug\dx12eframe.exe` (exit code: 1)
```

Here is minimal example:

Cargo.toml
```toml
[package]
name = "dx12eframe"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.28.0", features = ["wgpu"] }
env_logger = "0.11.5"
```

main.rs
```rust
use eframe::egui;

fn main() -> Result<(), eframe::Error> {
    env_logger::init();

    let native_options = eframe::NativeOptions {
        renderer: eframe::Renderer::Wgpu,
        wgpu_options: eframe::egui_wgpu::WgpuConfiguration {
            supported_backends: eframe::wgpu::Backends::DX12,
            ..Default::default()
        },
        ..Default::default()
    };

    eframe::run_simple_native("Hello world", native_options, move |ctx, _frame| {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading("Hello world");
        });
    })
}
```

It's only happening for me while using DX12 (GL and Vulkan works fine). But when I use only wgpu with winit (exactly code from [here](https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#first-some-housekeeping-state)) it works, so I guess it must be a bug in egui/eframe (that's why I post issue here).

**Desktop:**
 - OS: Windows 11 Pro 23H2
 - Version:  eframe 28 & 28.1 (I can't check older versions, because I have some compilation errors on versions <28)
 - Adapter info using wgpu: {
    name: "NVIDIA GeForce RTX 2070 SUPER",
    vendor: 4318,
    device: 7812,
    device_type: DiscreteGpu,
    driver: "31.0.15.4617",
    driver_info: "",
    backend: Dx12,
}

If there's anything else you need me to provide or check then just say :)

**Comment by kametsuu** [comment]
Okay, I found what the problem was. `Egui` has [all the default feature flags for crate `wgpu` disabled](https://github.com/emilk/egui/blob/master/Cargo.toml#L92), and in that case [only Vulkan and GLES backends are available on Windows (and Linux & Android)](https://github.com/gfx-rs/wgpu/issues/3514).


So in order to get DX12 working, I had to enable the default feature flags for wgpu in `Cargo.toml`:
```toml
[package]
name = "dx12eframe"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { git = "https://github.com/emilk/egui", branch = "master", features = [
    "wgpu",
] }
wgpu = { version = "22.0.0", default-features = true, features = [
    "fragile-send-sync-non-atomic-wasm",
] }
env_logger = "0.11.5"
```

I think this should be written somewhere in the documentation, because this behavior (for me, a newcomer to Rust) was very unclear and I spent so much time wondering what it could be, only to find out that it was just an unenabled feature flag.


Alternatively, I want to propose an approach that is used in `regex` Rust crate in which they solve it by simply re-exporting the dependency's feature flags of the `unicode` library, which is used by their underlying `regex-syntax` library thus allowing you to control the features by directly setting the feature flags for the `regex` crate.
See: [regex's Cargo.toml](https://github.com/rust-lang/regex/blob/1.4.2/Cargo.toml#L65-L89) and [regex-syntax's Cargo.toml](https://github.com/rust-lang/regex/blob/1.4.2/regex-syntax/Cargo.toml#L17-L32)
