### ISSUE TITLE
egui web demo 90% GPU usage on chrome on intel mac

### ISSUE THREAD

**Issue by hohowt** [emilk/egui#5058]
egui web demo 100% GPU usage on chrome on intel mac
```toml
[dependencies]
egui = "0.28.1"
eframe = { version = "0.28.1", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
serde = { version = "1.0.209", features = ["derive"] }

# web:
# [target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-futures = "0.4.43"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3.18"


[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
```

**Describe the bug**

**To Reproduce**
1. open egui.rs on intel mac chrome 
2. drag and move once

**Expected behavior**

**Screenshots**
<img width="1282" alt="图片" src="https://github.com/user-attachments/assets/3a3f5c32-66d3-4022-b4a4-c3267d0b75c1">
<img width="1035" alt="图片" src="https://github.com/user-attachments/assets/741932d1-9ed1-432e-8c30-694950a859e6">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version latest

**Additional context**
