### ISSUE TITLE
Layer sublayers have an invisible bounding box

### ISSUE THREAD

**Issue by MeGaGiGaGon** [emilk/egui#5135]
**Describe the bug**
The Pan Zoom demo currently has contained windows get stuck on the original container bounds in the north/west/northwest directions

**To Reproduce**
1. Go to egui.rs
2. Open the Pan Zoom window
3. Try to drag any contained window too far in any direction

**Expected behavior**
Sub-windows/sub-areas/sub-layers don't get stuck

**Screenshots**

Video of it being broken on egui.rs

https://github.com/user-attachments/assets/448bc404-833a-4683-8d6f-6743ceaf9ed0

Video of it being broken in my project which is based on the Pan Zoom demo

https://github.com/user-attachments/assets/56a957da-6895-4063-9d7a-8e403c4cc6f9

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: Version 1.69.162 Chromium: 128.0.6613.120 (Official Build) (64-bit)

**Additional context**
The bounds look to be related to OS? window shape, as my rectangular web browser has rectangular bounds, while my square project window has square bounds.

I currently have to do whatever this is to make eframe work on my computer 
```toml
eframe = { git = "https://github.com/emilk/egui.git", branch = "master", features = ["wgpu", "serde", "persistence"] }
wgpu = {version = "22.1.0", features=["angle"]}
```
