### ISSUE TITLE
egui image loaders uses too much ram

### ISSUE THREAD

**Issue by hacknus** [emilk/egui#5439]
We are working on a [file-dialog](https://github.com/fluxxcode/egui-file-dialog) with egui, and we want to browse through files while displaying a preview image of the selected file using egui-loaders.

When loading images with the egui loaders I see a huge memory increase.
After loading 10 images (each about 1 MB in size) the memory increases from 140 MB to 1.1 GB.

**Describe the bug**

**To Reproduce**
`cargo.toml`:

```toml
[dev-dependencies]
eframe = { version = "0.29.1", default-features = false, features = [
    "glow",
    "persistence",
] }
egui-file-dialog = { path = "." , features = ["information_view"]}
egui_extras = { version = "0.29", features = ["all_loaders"] }
# required by the egui loaders
image = { version = "0.25.5", features = ["bmp", "jpeg", "gif", "png", "tiff", "rayon"] }
```
But it also happens with the latest version on `master`.

```rust
let image = egui::Image::new(format!(
    "file://{}",
   path
));
ui.vertical_centered(|ui| {
    ui.add(image.max_height(ui.available_width()));
});
```

**Expected behavior**
I would assume that the RAM only increases in the same order as the size of the loaded files, not an order of magnitude more.

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1
 - Version 29
