### ISSUE TITLE
Image::from_uri fails CORS in 0.31.1, not 0.31.0

### ISSUE THREAD

**Issue by ctaggart** [emilk/egui#5829]
I'm using `ui.add(Image::from_uri(image_url));`, but with 0.31.1, it is failing to fetch the image with a failure in `ehttp::web::fetch_base` showing:

> Access to fetch at 'https://blah/' from origin 'chrome-extension://blah' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The error does *not* occur with 0.30.0 of egui_extras:
```toml
eframe = { version = "0.31.1", default-features = false, features = ["glow"] }
egui = { version = "0.31.1" }
egui_extras = { version = "0.31.0", features = ["http", "all_loaders"] }
```

The error occurs with 0.30.1 of egui_extras:
```toml
eframe = { version = "0.31.1", default-features = false, features = ["glow"] }
egui = { version = "0.31.1" }
egui_extras = { version = "0.31.1", features = ["http", "all_loaders"] }
```

The error occurs on the latest from master as well:
```toml
eframe = { path = "../../egui/crates/eframe", default-features = false, features = [
  "glow",
] }
egui = { path = "../../egui/crates/egui" }
egui_extras = { path = "../../egui/crates/egui_extras", features = [
  "http",
  "all_loaders",
] }
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
