### ISSUE TITLE
eframe::run_native crash for certain strings with persistence mode

### ISSUE THREAD

**Issue by minh-dng** [emilk/egui#5849]
**Describe the bug**

**To Reproduce**
Files:

**Cargo.toml**
```toml
[package]
name = "rust-learn"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31", default-features = false, features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
    "wayland",
] }
```

**main.rs**
```rust
use eframe::egui;

fn main() {
    let native_options = eframe::NativeOptions::default();
    eframe::run_native("DAIQUIRI", native_options, Box::new(|cc| Ok(Box::new(MyEguiApp::new(cc)))));
}

#[derive(Default)]
struct MyEguiApp {}

impl MyEguiApp {
    fn new(cc: &eframe::CreationContext<'_>) -> Self {
        // Customize egui here with cc.egui_ctx.set_fonts and cc.egui_ctx.set_visuals.
        // Restore app state using cc.storage (requires the "persistence" feature).
        // Use the cc.gl (a glow::Context) to create graphics shaders and buffers that you can use
        // for e.g. egui::PaintCallback.
        Self::default()
    }
}

impl eframe::App for MyEguiApp {
   fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
       egui::CentralPanel::default().show(ctx, |ui| {
           ui.heading("Hello World!");
       });
   }
}
```

(example in the [docs](https://docs.rs/eframe/0.31.1/eframe/index.html#usage-native), but change "My egui App" to "DAIQUIRI")

**Expected behavior**
Changing the string to not crash and display the folling in terminal (the "My egui App" string works, or "DAIQUIR")
```
xdg_wm_base@13: error 4: xdg_surface buffer (1920 x 1080) is larger than the configured fullscreen state (0 x 0)
Protocol error 4 on object xdg_wm_base@13: 
...
```

**Environment**
Windows 11, WSL
WSL version: 2.4.13.0
Kernel version: 5.15.167.4-1
WSLg version: 1.0.65
MSRDC version: 1.2.5716
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26100.1-240331-1435.ge-release
Windows version: 10.0.26100.3476

**Additional context**
The string that are causing the crashes are quite random? This behaviour exist in 0.31.0, I downgraded to 0.30, and tried to upgrade to 0.31.1 again, still having same issue.
`DAIQUIR I` also crashes, but `DAIQUIR A`, `DAIQUIR II` works

**Comment by Skgland** [comment]
Deleting the app.ron and setting `native_options.persist_window = false;` appears to work as a workaround, if one is fine with not restoring the window state, while still allowing to use the `persistence` feature.

**Comment by Skgland** [comment]
I think I have found how to reproduce this without the `persistence` feature enabled:

```rust
// src/main.rs
fn main() -> Result<(), eframe::Error> {
    eframe::run_native(
        "egui-panic",
        eframe::NativeOptions {
            viewport: eframe::egui::ViewportBuilder {
                fullscreen: Some(true),
                maximized: Some(false),
                ..Default::default()
            },
            ..Default::default()
        },
        Box::new(move |_cc| Ok(Box::new(EguiPanic {}))),
    )?;

    Ok(())
}

struct EguiPanic {}

impl eframe::App for EguiPanic {
    fn update(&mut self, _ctx: &eframe::egui::Context, _frame: &mut eframe::Frame) {}
}
```


```toml
# Cargo.toml

[package]
name = "egui-panic"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31", features = [
    "wayland",
    "glow",
], default-features = false }
```
