### ISSUE TITLE
macOS: eframe with_maximized(true) does not maximize when with_decorations(false) is passed in 0.31.x

### ISSUE THREAD

**Issue by willzeng274** [emilk/egui#7082]
**Describe the bug**
When using version 0.31.x, passing in `with_maximized(true)` to `eframe::egui::ViewportBuilder` no longer maxmizes window on macOS when `with_decorations(false)` is also passed into ViewportBuilder.

This issue does not exist when using versions 0.30, 0.29, 0.28, or 0.27.

**To Reproduce**
My Cargo.toml:
```toml
[package]
name = "eframe_issue"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { git = "https://github.com/emilk/egui", branch = "main" }
egui = { git = "https://github.com/emilk/egui", branch = "main" }
```

Minimal example to reproduce:
```rs
// main.rs
use eframe::NativeOptions;

struct TestApp {}

impl TestApp {
    fn new(_cc: &eframe::CreationContext<'_>) -> Self {
        Self {}
    }
}

impl eframe::App for TestApp {
    fn update(&mut self, ctx: &eframe::egui::Context, _frame: &mut eframe::Frame) {
        eframe::egui::CentralPanel::default().show(ctx, |ui| {
            ui.label("Test App");
        });
    }
}

fn main() -> Result<(), eframe::Error> {
    let native_options = NativeOptions {
        viewport: eframe::egui::ViewportBuilder::default()
            .with_maximized(true)
            .with_decorations(false) // if you comment this out, it works on 0.31.x
            .with_title("Test macOS maximization"),
        ..Default::default()
    };

    eframe::run_native(
        "Test macOS maximization",
        native_options,
        Box::new(|cc| Ok(Box::new(TestApp::new(cc)))),
    )
}
```

**Expected behavior**
The window is maximized and fills up the whole monitor.

**Screenshots**
What happens when you upgrade to 0.31.x:

![Image](https://github.com/user-attachments/assets/ac934d9f-36c3-4549-bbbb-15c82b0e3bcb)

The "correct" behaviour when you downgrade to 0.30.x:

![Image](https://github.com/user-attachments/assets/b1fee599-0576-42f6-8e66-af3e15ebfdc3)

**Desktop:**
 - OS: macOS Sequoia 15.1 (24B83)
