### ISSUE TITLE
toggle_switch example is no longer compile because of egui::Ui::is_rect_visible()

### ISSUE THREAD

**Issue by prx0** [emilk/egui#997]
Hi, I want to report an example of code which no longer compile because of breaking changes I think.

Here my Cargo.toml (I use eframe_template)
```toml
[package]
name = "eframe_template"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.15.0" # Gives us egui, epi and web+native backends

serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["persistence"]
persistence = ["eframe/persistence", "serde"] # Enable if you want to persist app state on shutdown

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# eframe = { path = "../egui/eframe" }

```
I was looking at the toggle_switch Widget here.
https://github.com/emilk/egui/blob/master/egui_demo_lib/src/apps/demo/toggle_switch.rs
You can see the function is_rect_visible from egui::UI used to ensure the component must be paint. 

But this function does not exist. It might be a function from a previous version of egui.

For my implementation, I use the method is_enable but I'm not sure to get the same behavior.

Here the code:
```rs
use eframe::egui;

pub fn toggle_ui(ui: &mut egui::Ui, on: &mut bool) -> egui::Response {
    let desized_size = ui.spacing().interact_size.y * egui::vec2(2.0, 1.0);

    let (rect, mut response) = ui.allocate_exact_size(desized_size, egui::Sense::click());
    
    if response.clicked() {
        *on = !*on;
        response.mark_changed();
    }

    response.widget_info(|| egui::WidgetInfo::selected(egui::WidgetType::Checkbox, *on, ""));

    if ui.is_enabled() {
        let how_on = ui.ctx().animate_bool(response.id, *on);
        let visuals = ui.style().interact_selectable(&response, *on);
        let rect = rect.expand(visuals.expansion);
        let radius = 0.5 * rect.height();
        
        ui.painter()
            .rect(rect, radius, visuals.bg_fill, visuals.bg_stroke);
    
        let circle_x = egui::lerp((rect.left() + radius)..=(rect.right() - radius), how_on);
        let center = egui::pos2(circle_x, rect.center().y);
        ui.painter()
            .circle(center, 0.75 * radius, visuals.bg_fill, visuals.fg_stroke);
    }
    response
}

pub fn toggle(on: &mut bool) -> impl egui::Widget + '_ {
    move |ui: &mut egui::Ui| toggle_ui(ui, on)
}
```

How can I be sure to paint the rect here ?

Thank you for reading and take care of you.
